# Kitty colors — Mint theme (Everforest)

foreground #d3c6aa
background #1e2326

selection_foreground #1e2326
selection_background #83c092

cursor #83c092
cursor_text_color #1e2326

url_color #7fbbb3

# Tab bar
active_tab_foreground   #1e2326
active_tab_background   #83c092
inactive_tab_foreground #d3c6aa
inactive_tab_background #272e33
tab_bar_background      #1e2326

# Normal colors
color0  #374145
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #d3c6aa

# Bright colors
color8  #4f585e
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #edeada
