# Mint theme for tmux — Everforest

set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#1e2326,fg=#d3c6aa"

set -g status-left-length 35
set -g status-left "#[fg=#1e2326,bg=#83c092,bold] ◈ #S #[fg=#83c092,bg=#1e2326,nobold]"

set -g status-right-length 85
set -g status-right "#[fg=#374145,bg=#1e2326]#[fg=#d3c6aa,bg=#374145] ⬡ #h #[fg=#7fbbb3,bg=#374145]#[fg=#1e2326,bg=#7fbbb3,bold] ✦ %b %d  %H:%M #[fg=#dbbc7f,bg=#7fbbb3]#[fg=#1e2326,bg=#dbbc7f,bold] ◆ #{battery_percentage} "

setw -g window-status-format "#[fg=#374145,bg=#1e2326]#[fg=#d3c6aa,bg=#374145] #I:#W #[fg=#374145,bg=#1e2326]"
setw -g window-status-current-format "#[fg=#83c092,bg=#1e2326]#[fg=#1e2326,bg=#83c092,bold] #I:#W #[fg=#83c092,bg=#1e2326]"
setw -g window-status-separator ""

set -g pane-border-style "fg=#272e33"
set -g pane-active-border-style "fg=#83c092"

set -g message-style "fg=#dbbc7f,bg=#1e2326,bold"
set -g mode-style "fg=#1e2326,bg=#83c092"
set -g copy-mode-match-style "fg=#1e2326,bg=#dbbc7f"
set -g copy-mode-current-match-style "fg=#1e2326,bg=#e67e80"
