# Rose theme for tmux — Rosé Pine

set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#191724,fg=#e0def4"

set -g status-left-length 30
set -g status-left "#[fg=#191724,bg=#eb6f92,bold] #S #[fg=#eb6f92,bg=#191724,nobold]"

set -g status-right-length 80
set -g status-right "#[fg=#403d52,bg=#191724]#[fg=#e0def4,bg=#403d52] #h #[fg=#9ccfd8,bg=#403d52]#[fg=#191724,bg=#9ccfd8,bold] %b %d  %H:%M #[fg=#f6c177,bg=#9ccfd8]#[fg=#191724,bg=#f6c177,bold] #{battery_percentage} "

setw -g window-status-format "#[fg=#403d52,bg=#191724]#[fg=#e0def4,bg=#403d52] #I:#W #[fg=#403d52,bg=#191724]"
setw -g window-status-current-format "#[fg=#eb6f92,bg=#191724]#[fg=#191724,bg=#eb6f92,bold] #I:#W #[fg=#eb6f92,bg=#191724]"
setw -g window-status-separator ""

set -g pane-border-style "fg=#26233a"
set -g pane-active-border-style "fg=#eb6f92"

set -g message-style "fg=#f6c177,bg=#191724,bold"
set -g mode-style "fg=#191724,bg=#eb6f92"
set -g copy-mode-match-style "fg=#191724,bg=#f6c177"
set -g copy-mode-current-match-style "fg=#191724,bg=#ea9a97"
